import StyleDictionary from 'style-dictionary';

/**
 * Emits a Tailwind v4 `@theme` block so Tailwind utilities are generated
 * directly from the token set — no duplicated scale in a JS config.
 */
StyleDictionary.registerFormat({
  name: 'css/tailwind-theme',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map(
      (t) => `  --${t.name}: ${t.value};`
    );
    return `/**\n * GENERATED by tokens/build.mjs — do not edit by hand.\n * Edit tokens/src/*.json and run \`npm run tokens\`.\n */\n@theme {\n${lines.join('\n')}\n}\n`;
  },
});

/**
 * Tailwind reads breakpoints from `--breakpoint-*`, colors from `--color-*`,
 * spacing from `--spacing-*`, etc. Our source names already align, so the
 * default `kebab` transform maps cleanly onto Tailwind's namespaces.
 */
export default {
  source: ['tokens/src/**/*.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/dist/',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
        {
          destination: 'theme.css',
          format: 'css/tailwind-theme',
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'tokens/dist/',
      files: [
        { destination: 'tokens.js', format: 'javascript/es6' },
        { destination: 'tokens.json', format: 'json/flat' },
      ],
    },
  },
};
